begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(20);
select is((select count(*)::integer from public.badge_definitions where criteria_version=1 and not retired and not blocked),24,'catalog has 24 active deterministic rules');
select is((select count(*)::integer from public.badge_definitions where retired and source_event='none'),15,'all 15 retired legacy keys remain readable');
select ok((select blocked from public.badge_definitions where badge_key='original_77_completed'),'undefined challenge completion remains blocked');
select is((select tier from public.badge_definitions where badge_key='iron_standard'),'bronze','one full day is foundational Bronze');
select is((select metric from public.badge_definitions where badge_key='check_ins_7'),'instance_check_in_count','progress counts posted check-ins instead of elapsed days');
select is((select scope from public.badge_definitions where badge_key='seven_sealed'),'challenge_instance','perfect streak awards are instance scoped');
select ok(not exists(select 1 from pg_indexes where schemaname='public' and indexname='user_badges_user_entry_date_unique'),'the one-badge-per-day cap is removed');
select ok((select relrowsecurity from pg_class where oid='public.user_badges'::regclass),'earned badges retain RLS');
select ok((select relrowsecurity from pg_class where oid='private.badge_app_visits'::regclass),'private canonical app visits have RLS defense in depth');
select ok(not has_table_privilege('authenticated','private.badge_app_visits','select'),'canonical visit history is not exposed');
select ok(not has_table_privilege('authenticated','public.user_badges','insert'),'members cannot forge awards');
select ok(not has_table_privilege('authenticated','public.user_badges','update'),'members cannot forge celebration state');
select ok(has_function_privilege('authenticated','public.get_badge_collection(uuid)','execute'),'members can request their catalog through the actor-checked RPC');
select ok(not has_function_privilege('anon','public.get_badge_collection(uuid)','execute'),'anonymous catalog access is denied');
select ok(has_function_privilege('authenticated','public.claim_badge_celebrations(uuid,uuid)','execute'),'members can lease unseen awards');
select ok(not has_function_privilege('anon','public.claim_badge_celebrations(uuid,uuid)','execute'),'anonymous celebration claims are denied');
select ok(has_function_privilege('authenticated','public.acknowledge_badge_celebrations(uuid,uuid,uuid[])','execute'),'members can acknowledge their leased awards');
select ok(not has_function_privilege('authenticated','public.award_badge(uuid,text,date,jsonb)','execute'),'generic badge forgery remains revoked');
select ok(not has_function_privilege('authenticated','private.persist_badge_event(uuid,text,uuid,text,date,timestamptz,jsonb,boolean)','execute'),'private canonical award persistence remains revoked');
select trigger_is('public','check_ins','award_check_in_badges_after_insert','private','award_check_in_badges','awards are evaluated after the canonical check-in exists');
select * from finish();
rollback;
