begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(30);
select is((select count(*)::integer from private.site_roles),2,'two initial site roles are canonical');
select is((select count(*)::integer from private.site_permissions),8,'eight initial permissions are explicit');
select is((select count(*)::integer from private.site_role_permissions where role_key='member'),0,'members have no admin permissions');
select is((select count(*)::integer from private.site_role_permissions where role_key='site_admin'),8,'site admins have the initial permission matrix');
select ok(not exists(select 1 from auth.users u where not exists(select 1 from private.site_user_roles r where r.user_id=u.id)),'every existing user has a canonical assignment');
select is((select count(*)::integer from private.site_admin_bootstrap_receipt),0,'migrations never bootstrap an administrator');
select ok((select relrowsecurity from pg_class where oid='private.site_user_roles'::regclass),'assignments have RLS defense in depth');
select ok((select relrowsecurity from pg_class where oid='private.site_admin_audit'::regclass),'audit has RLS defense in depth');
select ok((select relrowsecurity from pg_class where oid='private.site_admin_role_requests'::regclass),'retry records are private');
select ok((select relrowsecurity from pg_class where oid='private.site_admin_session_blocks'::regclass),'session blocks are private');
select ok(not has_table_privilege('authenticated','private.site_user_roles','update'),'members cannot directly grant roles');
select ok(not has_table_privilege('service_role','private.site_user_roles','update'),'service clients have no implicit role writer');
select ok(not has_table_privilege('authenticated','private.site_admin_audit','select'),'admin status does not grant direct audit reads');
select ok(not has_table_privilege('authenticated','private.site_admin_audit','update'),'admin status cannot alter audit history');
select ok(not has_function_privilege('anon','public.get_site_admin_context(uuid)','execute'),'anonymous readiness is denied');
select ok(has_function_privilege('authenticated','public.get_site_admin_context(uuid)','execute'),'members may request only their actor-checked readiness');
select ok(has_function_privilege('authenticated','public.site_admin_assign_role(uuid,uuid,text,bigint,uuid,uuid,text)','execute'),'role assignment enters a canonical permission/step-up boundary');
select ok(not has_function_privilege('anon','public.site_admin_assign_role(uuid,uuid,text,bigint,uuid,uuid,text)','execute'),'anonymous role mutation is denied');
select ok(not has_function_privilege('service_role','public.site_admin_assign_role(uuid,uuid,text,bigint,uuid,uuid,text)','execute'),'a service key alone cannot assign roles');
select ok(not has_function_privilege('authenticated','private.bootstrap_site_admin(uuid,uuid,text)','execute'),'bootstrap is not a member RPC');
select ok(not has_function_privilege('service_role','private.bootstrap_site_admin(uuid,uuid,text)','execute'),'bootstrap is not a service-key RPC');
select trigger_is('private','site_admin_audit','site_admin_audit_immutable','private','site_admin_immutable','audit rejects mutation even from ordinary operator SQL');
select trigger_is('auth','users','initialize_site_member','private','initialize_site_member','new Auth accounts receive member defaults');
select trigger_is('private','site_user_roles','guard_final_site_role','private','guard_site_admin_recovery','final-admin demotion is guarded at the data boundary');
select trigger_is('auth','users','guard_final_site_admin_auth','private','guard_site_admin_recovery','Auth delete and suspension preserve recovery');
select trigger_is('auth','mfa_factors','guard_final_site_admin_factor','private','guard_site_admin_factor_recovery','direct Auth unenrollment preserves final-admin recovery');
select ok(not has_function_privilege('authenticated','private.require_site_admin(text,uuid,boolean)','execute'),'internal authorization helper is not directly exposed');
select ok(not exists(select 1 from private.site_permissions where permission_key like 'journal.%' or permission_key like 'content.%'),'admin permissions confer no private-content access');
select ok((select relrowsecurity from pg_class where oid='private.site_admin_bootstrap_receipt'::regclass),'the one-time operator receipt has RLS defense in depth');
select ok((select relrowsecurity from pg_class where oid='private.site_admin_configuration'::regclass),'environment/origin configuration is not client-owned');
select * from finish();
rollback;
