"""Reproduce the Latin/UI subset without changing the licensed original font.

Requires fonttools[woff]==4.59.0 and brotli==1.1.0 in an isolated environment.
No dependencies are downloaded by this script. Run from any working directory.
"""
from hashlib import sha256
import json
from pathlib import Path

import fontTools
import brotli
from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
DIRECTORY = ROOT / "src/assets/fonts"
ORIGINAL = DIRECTORY / "InterVariable.woff2"
OUTPUT = DIRECTORY / "InterLatinUI.woff2"
ORIGINAL_SHA256 = "693b77d4f32ee9b8bfc995589b5fad5e99adf2832738661f5402f9978429a8e3"
UNICODES = "U+0000-00FF,U+2000-206F,U+20AC,U+2122,U+2190-21FF,U+2212,U+2215,U+2219,U+2300-27FF"

if fontTools.__version__ != "4.59.0":
    raise RuntimeError("Use pinned fonttools[woff]==4.59.0 for reproducible output.")
if brotli.__version__ != "1.1.0":
    raise RuntimeError("Use pinned brotli==1.1.0 for reproducible output.")
if sha256(ORIGINAL.read_bytes()).hexdigest() != ORIGINAL_SHA256:
    raise RuntimeError("Original Inter font differs from the reviewed upstream version.")

subset.main([str(ORIGINAL), f"--output-file={OUTPUT}", "--flavor=woff2",
             f"--unicodes={UNICODES}", "--layout-features+=tnum", "--no-recalc-timestamp"])
original = TTFont(ORIGINAL)
latin = TTFont(OUTPUT)
original_map = original.getBestCmap()
latin_map = latin.getBestCmap()
for codepoint, glyph in latin_map.items():
    if original["hmtx"][original_map[codepoint]] != latin["hmtx"][glyph]:
        raise RuntimeError(f"Subset changed text metrics for U+{codepoint:04X}.")
axes = lambda font: [(axis.axisTag, axis.minValue, axis.defaultValue, axis.maxValue)
                     for axis in font["fvar"].axes]
if axes(original) != axes(latin):
    raise RuntimeError("Subset changed variable-font axes.")
if OUTPUT.stat().st_size > 100_000:
    raise RuntimeError("Everyday UI font exceeded its 100 KB transfer budget.")


def unicode_ranges(codepoints):
    spans = []
    for value in sorted(codepoints):
        if spans and value == spans[-1][1] + 1:
            spans[-1][1] = value
        else:
            spans.append([value, value])
    return ",".join(f"U+{start:X}" if start == end else f"U+{start:X}-{end:X}"
                    for start, end in spans)


def face(filename, codepoints):
    return ("@font-face {\n"
            '  font-family: "Inter";\n'
            f'  src: url("./{filename}") format("woff2-variations");\n'
            "  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n"
            f"  unicode-range: {unicode_ranges(codepoints)};\n}}\n")


extended = set(original_map) - set(latin_map)
(DIRECTORY / "inter-fonts.css").write_text(
    "/* Generated by scripts/subset-ui-font.py. Preserve the original SIL license.\n"
    " * Extended-language glyphs load the unchanged original only when needed. */\n"
    + face(ORIGINAL.name, extended) + "\n" + face(OUTPUT.name, latin_map), encoding="utf-8")
(DIRECTORY / "inter-subset.json").write_text(json.dumps({
    "fontToolsVersion": fontTools.__version__, "brotliVersion": "1.1.0",
    "originalSha256": ORIGINAL_SHA256, "subsetSha256": sha256(OUTPUT.read_bytes()).hexdigest(),
    "unicodeSelection": UNICODES, "subsetBytes": OUTPUT.stat().st_size,
    "subsetGlyphCodepoints": len(latin_map), "extendedGlyphCodepoints": len(extended),
    "layoutFeatures": "fontTools defaults plus tnum", "axes": axes(latin),
}, indent=2) + "\n", encoding="utf-8")
print(f"Verified {OUTPUT.name}: {OUTPUT.stat().st_size} bytes; full glyph coverage retained.")
